### ISSUE TITLE
Pack error NU5017

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/reproducible-builds#28] opened 2022-11-18 14:06 UTC
When I use the `DotNet.ReproducibleBuilds` package(1.1.1), the pack step failed with error NU5017, when updated reference to `Microsoft.SourceLink.GitHub`, it works

```
error NU5017: Cannot create a package that has no dependencies nor content
```

![image](https://user-images.githubusercontent.com/7604648/202723212-3cd7ea64-5d26-480f-82b7-5ba878889b68.png)

Failed CI sample: 

https://github.com/WeihanLi/dotnet-exec/actions/runs/3489789242/jobs/5848009450

Success CI sample:

https://github.com/WeihanLi/dotnet-exec/actions/runs/3494529164/jobs/5850378023

code changes:

https://github.com/WeihanLi/dotnet-exec/commit/71d50edeb2de93cced08325567a20bd63196357d

**Comment by aetos382** [comment] 2022-12-12 15:40
I think this issue should be handled by the NuGet team.
Is this related to NuGet/Home#8583?

**Comment by Miguel-AgRz** [comment] 2024-05-16 09:21
I can confirm it, after removing 
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
I will not show the error anymore, i guess it is a bug

**Comment by MattKotsenas** [comment] 2024-07-02 17:08
Hi @WeihanLi! We've released a new version of the package which includes an updated version of `Microsoft.SourceLink.GitHub`. Since you mentioned that as a workaround for your issue, I'm resolving this issue. If you still experience problems after upgrading to the latest version, please open an issue and provide updated details such as a minimal repo / codebase that reproduces the issue.

Thanks!

**Closed by MattKotsenas** 2024-07-02 17:08 UTC
